// user
export const USER_SET_ISJWTVALID_SUCCESS = "USER_SET_ISJWTVALID_SUCCESS";
export const USER_SET_ISJWTVALID_ERROR = "USER_SET_ISJWTVALID_ERROR";
export const USER_SET_DEFAULT = "USER_SET_DEFAULT";
